module Main exposing (main)

import Gap
import Html exposing (Html)
import Html.Attributes.Classname exposing (classMixinWith)
import Mixin exposing (Mixin)
import Mixin.Html as Mixin
import Neat exposing (NoGap, View, setBoundary, setLayout)
import Neat.Layout as Layout
import Neat.Layout.Column as Column exposing (Column, column, defaultColumn)
import Neat.Layout.Row as Row exposing (Row, defaultRow, row, rowWithMap)
import Repl exposing (Repl, repl)
import Repl.Ast as Ast
import Repl.GapEditor as GapEditor exposing (GapEditor)
import Repl.ViewEditor as ViewEditor exposing (ViewEditor)



-- App


main : Program () Model Msg
main =
    Neat.element
        { init = \_ -> init
        , view = view
        , update = update
        , subscriptions = subscriptions
        , renderer =
            \_ ->
                { baseGapSize = "1rem"
                }
        }


type alias Model =
    { repl1 : Repl
    }


init : ( Model, Cmd Msg )
init =
    ( { repl1 =
            Repl.default
                |> Repl.setGapEditor defaultGapEditor
      }
    , Cmd.none
    )


defaultViewEditor : ViewEditor
defaultViewEditor =
    ViewEditor.fromAst
        Ast.Unselected


defaultGapEditor : GapEditor
defaultGapEditor =
    GapEditor.fromList
        [ ( "narrow"
          , { width = 0.4
            , height = 0.4
            }
          )
        , ( "wide"
          , { width = 2
            , height = 2
            }
          )
        ]


type Msg
    = UpdateRepl1 Repl.Msg


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        UpdateRepl1 new ->
            Repl.update new model.repl1
                |> Tuple.mapFirst (\r -> { model | repl1 = r })
                |> Tuple.mapSecond (Cmd.map UpdateRepl1)


view : Model -> View NoGap Msg
view model =
    repl UpdateRepl1 model.repl1
        |> setLayout Layout.fill
        |> setBoundary Gap.repl


subscriptions : Model -> Sub Msg
subscriptions _ =
    Sub.none



-- Helper functions


{-| A specialized version of `class` for this module.
It converts given class names into ones generated by CSS modules.
-}
class : String -> Mixin msg
class =
    classMixinWith <| \name -> "app__" ++ name
