module Main exposing (main)

import Ast exposing (Ast)
import Gap
import Html exposing (Html)
import Html.Attributes.Classname exposing (classMixinWith)
import Mixin exposing (Mixin)
import Mixin.Html as Mixin
import Neat exposing (NoGap, View, setBoundary, setLayout)
import Neat.Layout as Layout
import Neat.Layout.Column as Column exposing (Column, column, defaultColumn)
import Neat.Layout.Row as Row exposing (Row, defaultRow, row, rowWithMap)



-- App


main : Program () Model Msg
main =
    Neat.element
        { init = \_ -> init
        , view = view
        , update = update
        , subscriptions = subscriptions
        , renderer =
            \_ ->
                { baseGapSize = "1rem"
                }
        }


type alias Model =
    { ast : Ast
    }


init : ( Model, Cmd Msg )
init =
    ( { ast = Ast.Unselected
      }
    , Cmd.none
    )


type Msg
    = UpdateAst Ast.Msg


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        UpdateAst msg_ ->
            let
                ( ast_, cmd ) =
                    Ast.update msg_ model.ast
            in
            ( { model
                | ast = ast_
              }
            , Cmd.map UpdateAst cmd
            )


view : Model -> View NoGap Msg
view model =
    Ast.repl UpdateAst 2 model.ast
        |> setLayout Layout.fill
        |> setBoundary Gap.repl


subscriptions : Model -> Sub Msg
subscriptions _ =
    Sub.none



-- Helper functions


{-| A specialized version of `class` for this module.
It converts given class names into ones generated by CSS modules.
-}
class : String -> Mixin msg
class =
    classMixinWith <| \name -> "app__" ++ name
